### PR TITLE
ThrowsAsync: check exception on async methods

### PR DESCRIPTION
**Pull request by DiegoMartelli**
Hi,
I needed to check exception thrown by async methods and I was using your library, so I added required methods. I hope this help someone else, like @TheoConfidor asked in issue #8.
PS: This update target framework to 4.5

### CODE REVIEW

**Comment by bbraithwaite** [comment]
Great, thank you for adding this!

**Comment by DiegoMartelli** [comment]
I'm happy to help, I needed it and then shared :)
Let me know when you update nuget package

**Comment by bbraithwaite** [comment]
These changes are now available via: https://www.nuget.org/packages/MSTestExtensions/4.0.0

**Comment by DiegoMartelli** [comment]
Thank you @bbraithwaite

**Pull request merged**
